### ISSUE TITLE
send_and_request method does not honor stream argument

### ISSUE THREAD

**Issue by itsmemattchung** [sigmavirus24/betamax#77]
Is there a specific reason that stream argument is hard coded to `True` ?

Ran across this when adding **docstrings** in this pull request https://github.com/sigmavirus24/betamax/pull/76

https://github.com/sigmavirus24/betamax/blob/master/betamax/adapter.py#L97-L101

**Comment by sigmavirus24** [comment]
Yes. We also default stream to `True` because we always want to be able to retrieve the body of the request *exactly* as it came across the wire. This allows the `Content-Encoding` header to be stored without modification in the case where the request body is compressed. It preserves data integrity and allows us to implement other features (`preserve_exact_body_bytes`) with far less friction and far simpler logic.

**Comment by itsmemattchung** [comment]
Cool thanks for the explanation @sigmavirus24
